### ISSUE TITLE
Number of threads should be reduced - can be too late but reduced to...

### ISSUE THREAD

**Issue by clviper** [irsdl/IIS-ShortName-Scanner#13]
Hi there. I´m get this message on a particular host that I'm scanning.

I triggered shortname scanner with: 

> java -jar iis_shortname_scanner.jar 2 1 https://host

The scanner just keeps adding seconds to the sleep:

> Testing request method: "DEBUG" with magic part: "\a.aspx" ...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 3 seconds...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 4 seconds...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 5 seconds...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 6 seconds...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 7 seconds...
> Number of threads should be reduced - can be too late but reduced to:1
> Sleep for 8 seconds...
> 
> 

I am using the version 2.3.8.

**Comment by irsdl** [comment]
Hi,
This can be because of a firewall if I am not mistaken. You can always turn
on the debugging flag in the config file to see more details. You can also
use a web proxy such as Fiddler, Burp, or ZAP in front of it to see the
behaviour of the IIS server during the initial discovery phase (when it is
looking for the HTTP verb) and when it starts scanning for list of
files/directories.
I certainly cannot advise better than that as I cannot simulate this
behaviour in my lab (I have not seen it so far).

Thanks
Soroush

**Comment by clviper** [comment]
Thanks for the feedback.

I will try to debug this.

On Tue, Apr 5, 2016 at 2:33 PM, Soroush Dalili <notifications@github.com>
wrote:

> Hi,
> This can be because of a firewall if I am not mistaken. You can always turn
> on the debugging flag in the config file to see more details. You can also
> use a web proxy such as Fiddler, Burp, or ZAP in front of it to see the
> behaviour of the IIS server during the initial discovery phase (when it is
> looking for the HTTP verb) and when it starts scanning for list of
> files/directories.
> I certainly cannot advise better than that as I cannot simulate this
> behaviour in my lab (I have not seen it so far).
>
> Thanks
> Soroush
>
> On Mon, Apr 4, 2016 at 6:43 PM, clviper <notifications@github.com> wrote:
>
> > Hi there. I´m get this message on a particular host that I'm scanning.
> >
> > I triggered shortname scanner with:
> >
> > java -jar iis_shortname_scanner.jar 2 1 https://host
> >
> > The scanner just keeps adding seconds to the sleep:
> >
> > Testing request method: "DEBUG" with magic part: "\a.aspx" ...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 3 seconds...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 4 seconds...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 5 seconds...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 6 seconds...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 7 seconds...
> > Number of threads should be reduced - can be too late but reduced to:1
> > Sleep for 8 seconds...
> >
> > I am using the version 2.3.8.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/irsdl/IIS-ShortName-Scanner/issues/13>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/irsdl/IIS-ShortName-Scanner/issues/13#issuecomment-205806952>
>



-- 
Cláudio André
security.claudio.pt
