### ISSUE TITLE
Scanner with SSRF

### ISSUE THREAD

**Issue by Comancheroo** [irsdl/IIS-ShortName-Scanner#16]
Hello,

I want to scan with SSRF(Server Side Request Forgery).

URL: http://www.site.com/proxy.asp?url=http://192.168.10.5/
But your scanner can't scan to 192.168.10.5. Only site.com.

**Comment by irsdl** [comment]
I have added a new option called "useProvidedURLWithoutChange". Please change the config in order to use it.
