### ISSUE TITLE
Cookie mistake > I don't use "&" character in cookie

### ISSUE THREAD

**Issue by Comancheroo** [irsdl/IIS-ShortName-Scanner#22]
Hello,

I don't use "**&**" character in cookie(config.xml;entry key=cookies).

Note 1: Edit config.xml file to change the scanner settings, for instance to add additional headers.
Note 2: Sometimes it does not work for the first time and you need to try again.

**Comment by irsdl** [comment]
if you have XML special characters, you need to use HTML encoding or CDATA
