### ISSUE TITLE
Java 10 (& maybe 9) reflective access security policy errors

### ISSUE THREAD

**Issue by stuartw1** [irsdl/IIS-ShortName-Scanner#24]
Hi Soroush

Using OpenJDK10 the following error is produced. This may be due to additional java security restrictions. Am currently just using an older Java 8 JRE instead (as haven't got free time to triage) but thought it best to make you aware of the issue incase you want to take a look and fix it :)

Cheers

Stuart

----------------------------------------------------------------------------------

Scanning...

Testing request method: "DEBUG" with magic part: "\a.aspx" ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by IISShortNameScanner.IIS_ShortName_Scanner (file:/root/IIS-ShortName-Scanner/iis_shortname_scanner.jar) to field java.net.HttpURLConnection.method
WARNING: Please consider reporting this to the maintainers of IISShortNameScanner.IIS_ShortName_Scanner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by irsdl** [comment]
you just need to use some arguments. I have updated the package.
