### ISSUE TITLE
java  configuration

### ISSUE THREAD

**Issue by Bugspiderlee** [irsdl/IIS-ShortName-Scanner#25]
dose this tool only work wit java 7 and is there anywere this can be setup and running in a distro like kali linux
without java problems which might conflict with tools like burpsuite

**Comment by iNoSec2** [comment]
you can use multiple version of java in every linux distro, just google it ;)

**Comment by Bugspiderlee** [comment]
hey thanks for feedback dose it only work with java 7

**Comment by irsdl** [comment]
I have released a new version to work with Java17, give it a go
