### ISSUE TITLE
False-negatives in IIS Short Name (8.3) Scanner 2023.1

### ISSUE THREAD

**Issue by mohemiv** [irsdl/IIS-ShortName-Scanner#34]
Hi @irsdl,

I updated the IIS Short Name (8.3) scanner and I discovered that the current version may have false-negative results.

**Latest Version**
```
java -jar iis_shortname_scanner.jar 'https://target.remote/'
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
Do you want to use proxy [Y=Yes, Anything Else=No]? 
# IIS Short Name (8.3) Scanner version 2023.1 - scan initiated 2023/04/25 23:02:38
Target: https://target.remote/
|_ Result: Not vulnerable or no item was found. It was not possible to get proper/different error messages from the server. Check the inputs and try again.
|_ Extra information:
  |_ Number of sent requests: 2
```
```
OPTIONS /*~1*/a.aspx HTTP/1.1
Accept-Encoding: gzip, deflate
Host: target.remote
Connection: close
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
```
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html
Server: Microsoft-IIS/7.5
Date: Wed, 26 Apr 2023 04:02:36 GMT
Connection: close
Content-Length: 75

The page cannot be displayed because an internal server error has occurred.
```
```
OPTIONS /1234567890*~1*/a.aspx HTTP/1.1
Accept-Encoding: gzip, deflate
Host: target.remote
Connection: close
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
```
```
HTTP/1.1 200 OK
Allow: OPTIONS, TRACE, GET, HEAD, POST
Server: Microsoft-IIS/7.5
Public: OPTIONS, TRACE, GET, HEAD, POST
X-Powered-By: ASP.NET
Date: Wed, 26 Apr 2023 04:02:38 GMT
Connection: close
Content-Length: 0

```
**Older Version**
```
java -jar ./iis_shortname_scanner.jar 'https://target.remote/' 
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
# IIS Short Name (8.3) Scanner version 2.4 - scan initiated 2023/04/25 23:09:03
Target: https://target.remote/
|_ Result: Vulnerable!
|_ Used HTTP method: OPTIONS
|_ Suffix (magic part): /a.aspx
|_ Extra information:
  |_ Number of sent requests: 9
```
The older version is able to enumerate the files. The server's responses for the older version are the same as above.

**Comment by mohemiv** [comment]
I've tested the updated version and the acceptableDifferenceLengthBetweenResponses parameter and it doesn't looks like it solve the issue.

Anyway, you can test the tool on the `https://178.[DELETE].22.[REMOVE].91.[SKIP].155/` server. Please note that the company that own this server authorized researches to do test it for vulnerabilities and you are free to report any issues found on this server to the company.

**Comment by irsdl** [comment]
I think if you set `acceptableDifferenceLengthBetweenResponses` to `-1` in the config file, it will work. There is a bug in the cleaning RegEx at the moment which needs fixing. I will also add more flexibility around the cleaning area when removing dynamic values in the responses so it can handle different cases better.

**Comment by irsdl** [comment]
I have just updated it to version 2023.3 to mainly address this issue. Please let me know if you still have an issue and I will re-open this.
